Update requirements.txt
armsp/covid-vaccine-tracker pull request #2
Opened 2021-04-12 03:01 UTC by manvc

Hey I noticed you have used unicode library too. Thought it should be in the requirements.txt

2021-04-12 05:13 UTC, armsp requested changes

2021-04-12 05:13 UTC, armsp commented on requirements.txt
> +unicode
So, there is no library called `unicode`. Did you mean `unicodedata` ?

2021-04-14 17:09 UTC, manvc commented on requirements.txt
> +unicode
Sorry my bad. I meant unicodedata

2021-04-14 17:23 UTC, armsp commented on requirements.txt
> +unicodedata
So, `unicodedata` is part of the [standard library](https://docs.python.org/3/library/). So I don't think it's needed in the _requirements.txt_ file.

2021-04-15 05:33 UTC, armsp commented
Closing because no changes are required

2021-04-15 05:33 UTC, closed without merging